services:
  market-mysql:
    image: mysql:latest
    container_name: market-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: binance
    ports:
      - "3306:3306"
    networks:
      - orgwats-network

  market-service:
    image: 976193225338.dkr.ecr.ap-northeast-2.amazonaws.com/orgwats/market:latest
    container_name: market-service
    ports:
      - "50051:50051"
    networks:
      - orgwats-network
    depends_on:
      - market-mysql

  analyzer-service:
    image: 976193225338.dkr.ecr.ap-northeast-2.amazonaws.com/orgwats/analyzer:latest
    container_name: analyzer-service
    ports:
      - "50052:50052"
    networks:
      - orgwats-network
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - orgwats-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - orgwats-network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  orgwats-network:
    driver: bridge