services:
  market-mysql:
    image: mysql:latest
    container_name: market-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: binance
    ports:
      - "3306:3306"

  market-service:
    image: 976193225338.dkr.ecr.ap-northeast-2.amazonaws.com/orgwats/market:latest
    container_name: market-service
    ports:
      - "50051:50051"
    depends_on:
      - market-mysql

  analyzer-service:
    image: 976193225338.dkr.ecr.ap-northeast-2.amazonaws.com/orgwats/analyzer:latest
    container_name: analyzer-service
    ports:
      - "50052:50052"
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # kafka가 zookeeper에 커넥션하기 위한 대상을 지정
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock