services:
  market-mysql:
    image: mysql:latest
    container_name: market-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: binance
    ports:
      - "3306:3306"

  market-service:
    image: 976193225338.dkr.ecr.ap-northeast-2.amazonaws.com/orgwats/market:latest
    container_name: market-service
    ports:
      - "50051:50051"
    depends_on:
      - market-mysql

  analyzer-service:
    image: 976193225338.dkr.ecr.ap-northeast-2.amazonaws.com/orgwats/analyzer:latest
    container_name: analyzer-service
    ports:
      - "8080:8080"
      - "50052:50052"

  order-service:
    image: 976193225338.dkr.ecr.ap-northeast-2.amazonaws.com/orgwats/order:latest
    container_name: order-service