name: AWS Deploy

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Deployment 레포 체크아웃
      - name: Checkout Deployment Repository
        uses: actions/checkout@v4
        with:
          repository: orgwats/deployment
          token: ${{ secrets.GITHUB_TOKEN }}
          path: deployment

      # 2. Config 가져오기
      - name: Fetch Config from Lambda
        run: |
          curl -s "${{ secrets.CONFIG_API_URL }}/config" -o deployment/config.json


      # 3. Install yq and jq
      - name: Install yq and jq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          sudo apt-get update && sudo apt-get install -y jq

      # 4. Generate docker-compose.yml
      - name: Generate docker-compose.yml
        run: |
          cd deployment
          chmod +x scripts/generate-compose.sh
          ./scripts/generate-compose.sh aws

      # 5. EC2 docker-compose.yml 배포
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deployment/docker-compose.yml"
          target: "~/"