name: Deploy Service

on:
  repository_dispatch:
    types: [ deploy ]

jobs:
  deploy-market:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout Service Repository
        uses: actions/checkout@v4
        with:
          repository: orgwats/${{ github.event.client_payload.service }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.client_payload.service }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::976193225338:role/deployment
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: orgwats/${{ github.event.client_payload.service }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ${{ github.event.client_payload.service }}
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/"