name: Deploy Market Service

on:
  repository_dispatch:
    types: [ deploy-market ]

jobs:
  deploy-market:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout Market Service Repository
        uses: actions/checkout@v4
        with:
          repository: orgwats/market
          token: ${{ secrets.GITHUB_TOKEN }}
          path: market

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::976193225338:role/deployment
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: orgwats/market
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG